### ISSUE TITLE
asa_ros node is not triggering image subscription callback

### ISSUE THREAD

**Issue by EricVoll** [microsoft/azure_spatial_anchors_ros#10]
Hi :)

I am currently trying to get asa_ros running on the setup described below.
The problem is, that the asa_ros node successfully initializes, but then does nothing. Debugging showed, that the image/camera_info callback is never invoked. 

rqt_graph shows that the asa_ros node is correclty subscribing to the correct topics (via remapping in the launch file)
![image](https://user-images.githubusercontent.com/28082576/108598324-5810a180-738d-11eb-8d3f-3361bb9a5276.png)

This is the relevant part of the launch file, where you can see the remapping of the topics.
```
<arg name="print_status" default="true" />
<node name="asa_ros" type="asa_ros_node" pkg="asa_ros" output="screen" clear_params="true">
    <remap from="image" to="versavis/cam0/image_raw" />
    <remap from="camera_info" to="versavis/cam0/camera_info" />

    <!-- The frame ID of your world/odometry frame. Should be static relative to, well, the world. -->
    <param name="world_frame_id" value="world" />
    <!-- Optical frame of the camera, z facing "forward" (out of the camera frame). -->
    <param name="camera_frame_id" value="camera0" />
    [...]
</node>
```

When launching `roslaunch asa_ros asa_ros.launch` everything startup nicely, but then  just stops to do anything. The callback in the synchronized image/camera_info callback is never called.

I checked the following:
- I can lookup the tf between the tf frames `world` and `camera0` (Which is also what the ros wrapper does in the callback) and the tf exists/can be resolved. The frames are also correctly drawn in rviz
- I can `rostopic echo` the required topics (`versavis/cam0/image_raw` of type sensor_msgs/Image and `versavis/cam0/camera_info` of type sensor_msgs/CameraInfo) and the terminal prints tons of data. The header-time-stamps also are the same.
- The asa_ros node is not running inside a namespace  
- I do know, that the linux SDK requires undistorted images, and that my images are not undistorted yet, but the message types are the same so I assume that this would not change anything currently. (right?)

Am I missing something? Do you have any idea what could be wrong?
Thanks in advance,
Eric

---------------
My setup:
Intel NUC with AMD architecture, Ubuntu 18.04, ROS Melodic
Flir Camera

--------------
Terminal output of the asa_ros node:
```
process[asa_ros-1]: started with pid [28792]
[ INFO] [1613830867.870088335]: Subscribing to mapped image topic
[ INFO] [1613830867.879779699]: Account domain: SomeURL account ID: NotGoodForGitHub account key:AlsoNotGoodForGitHub
I0220 14:21:07.881736 28811 asa_interface.cpp:458] ----------------------------------------------------------
I0220 14:21:07.881778 28811 asa_interface.cpp:459]       ReadyForCreateProgress : 0
I0220 14:21:07.881817 28811 asa_interface.cpp:461] RecommendedForCreateProgress : 0
I0220 14:21:07.881831 28811 asa_interface.cpp:463]                 UserFeedback : SessionUserFeedback::NotEnoughMotion
[ INFO] [1613830867.882225986]: Now done with ctor
[ INFO] [1613830867.882250994]: [Azure Spatial Anchors ROS] Now running.
{No new output until I kill it manually}
^C[asa_ros-1] killing on exit
```
(Note: I added a few `ROS_INFO` calls while debugging, but did not change anything else. When git-resetting to the current master the same thing happens)

----------------
# Edit:
On further debugging: I added a subscriber for the `image` and `camera_info` topic and the node receives the data correctly. So I guess there is something wrong with the synchronizer. I'll dig deeper there.

**Comment by EricVoll** [comment]
Ok I found the issue. The Wiki says that the timestamps have to be exactly equal. I modified the source code to use a Synchronizer with an AproximateTime Policy, which solved the isse (my timestamps are off about 1ms).

I'll create a PR with that as an optional param if you want me to.

**Comment by jeffdelmerico** [comment]
That sounds like the problem as well as the correct solution for it.  Normally this should be addressed in the camera publisher, since the camera_info messages shouldn't be changing, so they should just be published at the same time as the image.  But some publishers don't sync them properly and you end up with this situation.  

If you've already implemented this, a PR to address this would be great. Thanks @EricVoll!
