### ISSUE TITLE
404 in Wiki link

### ISSUE THREAD

**Issue by EricVoll** [microsoft/azure_spatial_anchors_ros#16]
The link to the Azure Portal in [this Wiki page](https://github.com/microsoft/azure_spatial_anchors_ros/wiki#pre-requisites) returns an Error 404.
Should it be this link instead?: https://portal.azure.com/

**Comment by jeffdelmerico** [comment]
Thanks for catching this.  I do remember the old link working, but it probably should have been portal.azure.com from the beginning.  I've updated it now, so please double-check that it works for you and then I'll close this.

**Comment by EricVoll** [comment]
Yup, looks good 👍
