### ISSUE TITLE
Question about using output poses from SLAM for to create an anchor

### ISSUE THREAD

**Issue by zaalsabb** [microsoft/azure_spatial_anchors_ros#21]
Hi, 

I've been running into accuracy issues when I try to create an anchor. I'm running RGBD orbslam2  with an Azure Kinect. I use the output poses from orbslam2 to create an anchor.

The issue that I'm having is that whenever orbslam2 performs loop closure, the poses received by asa_ros are not updated, which causes the anchor localization to be inaccurate. Is there a way to have asa_ros re-check the tf2 messages it previously received and then request the updated tf2 poses after loop closure is performed? Or is this performed automatically already by the asa_ros node?

Thanks

**Comment by zaalsabb** [comment]
Yes, although I don't think it is possible to update an anchor once it is created on Azure cloud's side. The user would need to create a new anchor with the corrected poses. I'm just wondering if it is possible for asa_ros to read the corrected camera tf2 transforms for images that it received already. It would be possible since tf2 allows you to get transforms in the past.

**Comment by EricVoll** [comment]
As far as I know, you cannot update the anchor itself no. Querying the same anchor repeatedly improves the features used to find the anchor though, but that happens silently in the background.

As you can see [here](https://github.com/microsoft/azure_spatial_anchors_ros/blob/f5e0f87445b6e9072479be30b51e3c1e205703e0/asa_ros/src/asa_ros_node.cpp#L159) the ros node does not buffer the images. It instantly forwards them to the linux sdk. You could implement some sort of buffer and then re-submit the image - the ros wrapper uses tf2 to lookup the pose using the image's timestamp, so you wouldn't have to handle the new poses, if your SLAM library updates the past-tf2-frames as well. In that case I would suggest resetting the ASA session before doing so, just to make sure that the old server-side point cloud doesn't negatively influence the performance (there is a [ros-service](https://github.com/microsoft/azure_spatial_anchors_ros/blob/f5e0f87445b6e9072479be30b51e3c1e205703e0/asa_ros/src/asa_ros_node.cpp#L96) for that).

**Comment by zaalsabb** [comment]
Okay, thank you for the suggestion. That pretty much answers my question!
