### ISSUE TITLE
Strings in message and service and definitions

### ISSUE THREAD

**Issue by RobertBlakeAnderson** [microsoft/azure_spatial_anchors_ros#23]
Currently in definitions such as FindAnchor.srv, the client is required to concatenate a string of semicolon-separated IDs in order to reference multiple anchors.

I propose it would be better practice for the server to take a vector of IDs. If the backend requires the combined string, it should be created within the ROS service callback.

**Comment by jeffdelmerico** [comment]
Thanks for the suggestion.  The request to the cloud service does need to be in the form of a concatenated string of uuids, but I think your proposal to expose this as a vector instead would be a bit easier to use.

Tagging @EricVoll in case he can add that feature in the near future.  But please feel free to implement it yourself and create a PR if this functionality is relevant for your use case.

**Comment by RobertBlakeAnderson** [comment]
I'm willing to make a PR. Initially I'll add the vector member and deprecation warnings on the current string member, so that we don't break existing clients. I'll make a note to make another PR in a few months to actually remove the string.

**Comment by jeffdelmerico** [comment]
Great! That sounds like a good plan.

**Comment by EricVoll** [comment]
Thanks @RobertBlakeAnderson  for helping out!
