### ISSUE TITLE
Is there plans for ROS2 and Windows Support?

### ISSUE THREAD

**Issue by Levi-Armstrong** [microsoft/azure_spatial_anchors_ros#4]
Currently we have several projects leveraging ROS2 and the Hololens 2 and I believe this could be a useful on these projects if support was added for Windows and ROS2.

**Comment by helenol** [comment]
Hi @Levi-Armstrong!
ROS2 would be relatively straight forward (it's just a wrapper :) and the internal interface is anyway ROS-independent: https://github.com/microsoft/azure_spatial_anchors_ros/blob/main/asa_ros/include/asa_ros/asa_interface.h , just need to pass in cv::Mat and Eigen::Affine3d frames), we would also welcome PRs if you wanted to do this.
Windows support is a bit trickier, as we'd have to build a different version of the underlying SDK binaries. We are definitely thinking about this though.
It works just fine under WSL/WSL2 if that would be a feasible short-term solution to your problem.

**Comment by Levi-Armstrong** [comment]
Thank you for the information.
