### ISSUE TITLE
Demo Instructions on Wiki are slightly wrong

### ISSUE THREAD

**Issue by menace102** [microsoft/azure_spatial_anchors_ros#7]
The instructions on the Demo page reference the node type, not the node name. I was able to get things to run using `rosservice call /asa_ros/create_anchor`, instead of `rosservice call /asa_ros_node/create_anchor`. Is this correct?

Additionally, while trying to launch the demos, it looks the parameter names for account information doesn't have underscores in the launch file. Using `_account_id` instead of `account_id` gave me server errors. 

Otherwise, cool demo! Thanks for sharing!

Franklin Wu

**Comment by PattyUnity** [comment]
@menace102 Thank you for sharing. 
I encountered the same thing and your comment solved the issues.

**Comment by jeffdelmerico** [comment]
Thanks for raising this issue.  Apologies that it took a bit of time to resolve, despite being straightforward.

I've resolved the inaccurate instructions that you mentioned, and a few other things:

-  Several of the instances of rosservice and rostopic calls used `/asa_ros_node/...` when the node namespace is just `asa_ros`. 
- The first instruction to run the launch file had underscores on the input arguments (the syntax for if they were actually params not args).
- Calling the create anchor service without providing a transform is ok, but you still need to give the name of the odom frame, the request argument can't be empty.
- Some other edits to make it (hopefully) easier to use.

Please have a look, and give the updates a try to be sure they work for you.
